### ISSUE TITLE
Invalid context `_radiumStyleKeeper` of type `StyleKeeper` supplied to `Grid`

### ISSUE THREAD

**Issue by choonchernlim** [FormidableLabs/radium-grid#28] opened 2016-04-05 14:24 UTC
I'm trying out with this simple example:-

```
import { StyleRoot } from 'radium';
import { Grid, Cell } from 'radium-grid';
import React from 'react';

export default () => (
  <StyleRoot>
    <Grid>
      <Cell>
        <p>Lorem</p>
      </Cell>
      <Cell>
        <p>ipsum</p>
      </Cell>
      <Cell>
        <p>dolor</p>
      </Cell>
      <Cell>
        <p>sit</p>
      </Cell>
    </Grid>

  </StyleRoot>
);
```
It renders fine, but I'm seeing this error in the console:-

```
warning.js:45 Warning: Failed Context Types: Invalid context `_radiumStyleKeeper` of type `StyleKeeper` supplied to `Grid`, expected instance of `StyleKeeper`. Check the render method of `StatelessComponent`.
```

I'm using v1.1.0.

Thank you.

**Comment by alexlande** [comment] 2016-04-06 23:32
Thanks @choonchernlim! Could you confirm what version of React you're using? If you were using an old version with owner-based context I could see that causing problems in this case, but I wouldn't expect to see this if you're using React 0.14 or higher.

Any ideas on this one @tptee?

**Comment by choonchernlim** [comment] 2016-04-06 23:39
I'm using React v0.14.8. I do run through my ES6 files through Babel using Webpack. 

Would that be a problem?

**Comment by DaveyEdwards** [comment] 2016-04-07 01:50
I am on React v.0.14.7 and getting this

**Comment by tptee** [comment] 2016-04-08 03:24
@choonchernlim @DaveyEdwards 
> Invalid context `_radiumStyleKeeper` of type `StyleKeeper` supplied to `Grid`, expected instance of `StyleKeeper`.

The problem is here: https://github.com/FormidableLabs/radium/issues/575#issuecomment-184462379

> the issue is that you have 2 different versions of Radium in your frontend bundle. So the React.PropTypes.instanceOf(Radium.StyleKeeper) check doesn't work because you have Radium1.StyleKeeper and Radium2.StyleKeeper which are at different locations in memory

I'm closing this since it doesn't appear to be a problem with `radium-grid`. Can you both try reproducing this after you've confirmed that there's only one `radium` included in your bundle? I'll reopen if we still run into the issue.

**Closed by tptee** 2016-04-08 03:24 UTC
Labels: bug

**Comment by choonchernlim** [comment] 2016-04-08 12:34
You are indeed right. I have both `radium` and `radium-grid` in my `package.json`. Upon removing `radium`, the error goes away.

Thank you for the clarification.

**Comment by DaveyEdwards** [comment] 2016-04-08 20:40
Working here as well thanks.  

Just to clarify I removed radium from node_modules/radium-grid/package.json to get it working.  Also worked with putting it inside a "peerDependencies": { "radium": "^0.16"}} in the same package.json (never used peer before and not sure if that did anything differently)

I am using radium so removing it from my projects package.json throws other errors, and could not get it working with doing a peer dependency in it.

**Comment by alexlande** [comment] 2016-04-08 20:42
Yeah, the last version of `radium-grid` used `radium` as a normal dependency instead of a peer dependency, so if you were using a different version of Radium in your app you would end up with two copies. In the just released `radium-grid` `2.0.0`, Radium is included as a peer dependency, so the issue shouldn't pop up anymore once you upgrade.

**Comment by alvincrespo** [comment] 2016-06-22 02:20
Hmm. This is very strange when I do an `npm link` with my component library. Any information that I can provide that might be useful?

**Comment by FarhadG** [comment] 2016-09-05 23:09
People still having this issue? I've tried the peerDependency approach, however, still no luck, unless I'm doing something wrong:

```
warning.js:36Warning: Failed context type: Invalid context `_radiumStyleKeeper` of type `StyleKeeper` supplied to `Component`
```

I have a `sample-ui-library` that uses radium and here's a sample `package.json`:

```json
  "dependencies": {
    "radium": "0.18.1",
    "react": "~15.2.1",
    "react-dom": "^15.3.1",
  },
  "peerDependencies": {
    "radium": "0.18.1"
  },
```

and my main project in a separate repo with the following sample `package.json`:

```json
  "dependencies": {
    "sample-ui-library": "0.5",
    "radium": "0.18.1"
  },
```

Still getting the same warning, unless I'm missing something. Thanks in advance for your suggestions.

**Comment by Matthew-Burfield** [comment] 2017-08-28 02:32
I was getting this error because I accidentally stuffed up my import.
I had `import Radium from 'Radium'` instead of `import Radium from 'radium'` (capital R).

Silly error, I know. But fixing that incorrect import fixed this error.
